#!/bin/bash

purge_list=(
	*-mozc
	*mythes*
	akregator
	anthy-common
	aspell-am
	aspell-ar
	aspell-ar-large
	aspell-bg
	aspell-bn
	aspell-ca
	aspell-cs
	aspell-cy
	aspell-da
	aspell-de
	aspell-el
	aspell-eo
	aspell-es
	aspell-et
	aspell-eu
	aspell-fa
	aspell-fr
	aspell-ga
	aspell-gl-minimos
	aspell-gu
	aspell-he
	aspell-hi
	aspell-hr
	aspell-hu
	aspell-is
	aspell-it
	aspell-kk
	aspell-ku
	aspell-lt
	aspell-lv
	aspell-ml
	aspell-mr
	aspell-nl
	aspell-no
	aspell-pa
	aspell-pl
	aspell-pt-br
	aspell-ro
	aspell-ru
	aspell-sk
	aspell-sl
	aspell-sv
	aspell-ta
	aspell-te
	aspell-tl
	aspell-uk
	busybox
	debian-reference-common
	dragonplayer
	fakeroot
	firefox*
	gimp*
	goldendict
	hspell
	hunspell*
	ibrazilian
	ibritish
	ibulgarian
	icatalan
	idanish
	idutch
	ifrench-gut
	ihungarian
	iitalian
	ilithuanian
	imagemagick*
	ingerman
	inorwegian
	ipolish
	irussian
	ispanish
	iswiss
	juk
	kaddressbook
	kdeconnect
	khelpcenter
	kmag
	kmail
	kmousetool
	kmouth
	knotes
	konqueror
	kontrast
	korganizer
	kwalletmanager
	kwrite
	libreoffice*
	manpages-*
	mariadb-common
	mlterm-common
	mozc-*
	myspell*
	pim-data-exporter
	pim-sieve-editor
	plasma-vault
	plasma-widgets-addons
	speech-dispatcher
	sweeper
	task-albanian-desktop
	task-amharic
	task-amharic-desktop
	task-amharic-kde-desktop
	task-arabic
	task-arabic-desktop
	task-arabic-kde-desktop
	task-asturian
	task-asturian-desktop
	task-basque
	task-basque-desktop
	task-basque-kde-desktop
	task-belarusian
	task-belarusian-desktop
	task-belarusian-kde-desktop
	task-bengali
	task-bengali-desktop
	task-bengali-kde-desktop
	task-bosnian
	task-bosnian-desktop
	task-bosnian-kde-desktop
	task-brazilian-portuguese
	task-brazilian-portuguese-desktop
	task-brazilian-portuguese-kde-desktop
	task-british-desktop
	task-british-kde-desktop
	task-bulgarian
	task-bulgarian-desktop
	task-bulgarian-kde-desktop
	task-catalan
	task-catalan-desktop
	task-catalan-kde-desktop
	task-chinese-s
	task-chinese-s-desktop
	task-chinese-s-kde-desktop
	task-chinese-t
	task-chinese-t-desktop
	task-chinese-t-kde-desktop
	task-croatian
	task-croatian-desktop
	task-croatian-kde-desktop
	task-cyrillic
	task-cyrillic-desktop
	task-cyrillic-kde-desktop
	task-czech
	task-czech-desktop
	task-czech-kde-desktop
	task-danish
	task-danish-desktop
	task-danish-kde-desktop
	task-dutch
	task-dutch-desktop
	task-dutch-kde-desktop
	task-dzongkha-desktop
	task-dzongkha-kde-desktop
	task-esperanto
	task-esperanto-desktop
	task-esperanto-kde-desktop
	task-estonian
	task-estonian-desktop
	task-estonian-kde-desktop
	task-finnish
	task-finnish-desktop
	task-finnish-kde-desktop
	task-french
	task-french-desktop
	task-french-kde-desktop
	task-galician
	task-galician-desktop
	task-galician-kde-desktop
	task-georgian-desktop
	task-german
	task-german-desktop
	task-german-kde-desktop
	task-greek
	task-greek-desktop
	task-greek-kde-desktop
	task-gujarati
	task-gujarati-desktop
	task-gujarati-kde-desktop
	task-hebrew
	task-hebrew-desktop
	task-hebrew-kde-desktop
	task-hindi
	task-hindi-desktop
	task-hindi-kde-desktop
	task-hungarian
	task-hungarian-desktop
	task-hungarian-kde-desktop
	task-icelandic
	task-icelandic-desktop
	task-icelandic-kde-desktop
	task-indonesian-desktop
	task-indonesian-kde-desktop
	task-irish
	task-irish-desktop
	task-irish-kde-desktop
	task-italian
	task-italian-desktop
	task-italian-kde-desktop
	task-japanese
	task-japanese-desktop
	task-japanese-kde-desktop
	task-kannada-desktop
	task-kannada-kde-desktop
	task-kazakh
	task-kazakh-desktop
	task-kazakh-kde-desktop
	task-khmer
	task-khmer-desktop
	task-khmer-kde-desktop
	task-korean
	task-korean-desktop
	task-korean-kde-desktop
	task-kurdish
	task-kurdish-desktop
	task-kurdish-kde-desktop
	task-latvian
	task-latvian-desktop
	task-latvian-kde-desktop
	task-lithuanian
	task-lithuanian-desktop
	task-lithuanian-kde-desktop
	task-macedonian
	task-macedonian-desktop
	task-macedonian-kde-desktop
	task-malayalam
	task-malayalam-desktop
	task-malayalam-kde-desktop
	task-marathi
	task-marathi-desktop
	task-nepali-desktop
	task-nepali-kde-desktop
	task-northern-sami
	task-northern-sami-desktop
	task-norwegian
	task-norwegian-desktop
	task-norwegian-kde-desktop
	task-persian
	task-persian-desktop
	task-persian-kde-desktop
	task-polish
	task-polish-desktop
	task-polish-kde-desktop
	task-portuguese
	task-portuguese-desktop
	task-portuguese-kde-desktop
	task-punjabi
	task-punjabi-desktop
	task-punjabi-kde-desktop
	task-romanian
	task-romanian-desktop
	task-romanian-kde-desktop
	task-russian
	task-russian-desktop
	task-russian-kde-desktop
	task-serbian
	task-serbian-desktop
	task-serbian-kde-desktop
	task-sinhala-desktop
	task-sinhala-kde-desktop
	task-slovak
	task-slovak-desktop
	task-slovak-kde-desktop
	task-slovenian
	task-slovenian-desktop
	task-slovenian-kde-desktop
	task-south-african-english-desktop
	task-spanish
	task-spanish-desktop
	task-spanish-kde-desktop
	task-swedish
	task-swedish-desktop
	task-swedish-kde-desktop
	task-tagalog
	task-tamil
	task-tamil-desktop
	task-telugu
	task-telugu-desktop
	task-telugu-kde-desktop
	task-thai
	task-thai-desktop
	task-thai-kde-desktop
	task-turkish
	task-turkish-desktop
	task-turkish-kde-desktop
	task-ukrainian
	task-ukrainian-desktop
	task-ukrainian-kde-desktop
	task-uyghur-desktop
	task-uyghur-kde-desktop
	task-vietnamese-desktop
	task-vietnamese-kde-desktop
	task-welsh
	task-welsh-desktop
	task-xhosa-desktop
	task-xhosa-kde-desktop
	vim-common
	wbrazilian
	wbulgarian
	wcatalan
	wdanish
	wdutch
	wfrench
	witalian
	wngerman
	wnorwegian
	wpolish
	wspanish
	wswedish
	xiterm+thai
	xterm
)

install_list=(
	flatpak
	mkvtoolnix-gui
	qbittorrent
	synaptic
	vlc
)

sudo apt purge "${purge_list[@]}" -y

sudo apt autoremove -y # Uninstalls unused APT dependencies
sudo apt update -y     # Fetches the latest APT package lists
sudo apt upgrade -y    # Installs the latest version of installed APT packages

sudo apt install "${install_list[@]}" -y
sudo apt clean -y # Deletes all cached APT packages

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.brave.Browser com.discordapp.Discord com.valvesoftware.Steam com.vscodium.codium -y
